/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lyh_dclock_MainActivity */

#ifndef _Included_org_lyh_dclock_MainActivity
#define _Included_org_lyh_dclock_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lyh_dclock_MainActivity
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lyh_dclock_MainActivity_helloJni
  (JNIEnv *, jclass);

/*
 * Class:     org_lyh_dclock_MainActivity
 * Method:    addCalc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_lyh_dclock_MainActivity_addCalc
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
